import { Customer } from './types';

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    address: '12, MG Road, Bangalore',
    createdAt: '2024-08-15',
    loans: [
      {
        id: 'l1',
        customerId: '1',
        itemName: 'Gold Necklace',
        category: 'gold',
        purity: '22K',
        weightGrams: 45,
        marketRate: 6200,
        loanAmount: 200000,
        interestRate: 1.5,
        startDate: '2024-08-15',
        status: 'active',
        payments: [
          { id: 'p1', loanId: 'l1', amount: 3000, date: '2024-09-15', type: 'interest' },
          { id: 'p2', loanId: 'l1', amount: 3000, date: '2024-10-15', type: 'interest' },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'Priya Sharma',
    phone: '+91 87654 32109',
    address: '45, Anna Nagar, Chennai',
    createdAt: '2024-06-20',
    loans: [
      {
        id: 'l2',
        customerId: '2',
        itemName: 'Silver Anklets (Pair)',
        category: 'silver',
        purity: '92.5%',
        weightGrams: 120,
        marketRate: 78,
        loanAmount: 8000,
        interestRate: 2,
        startDate: '2024-06-20',
        status: 'closed',
        payments: [
          { id: 'p3', loanId: 'l2', amount: 8500, date: '2024-09-20', type: 'full' },
        ],
      },
      {
        id: 'l3',
        customerId: '2',
        itemName: 'Gold Bangles',
        category: 'gold',
        purity: '18K',
        weightGrams: 30,
        marketRate: 5100,
        loanAmount: 120000,
        interestRate: 1.5,
        startDate: '2025-01-10',
        status: 'active',
        payments: [],
      },
    ],
  },
  {
    id: '3',
    name: 'Mohammed Ali',
    phone: '+91 76543 21098',
    address: '78, Jubilee Hills, Hyderabad',
    createdAt: '2024-03-05',
    loans: [
      {
        id: 'l4',
        customerId: '3',
        itemName: 'Gold Chain',
        category: 'gold',
        purity: '22K',
        weightGrams: 25,
        marketRate: 6200,
        loanAmount: 100000,
        interestRate: 1.5,
        startDate: '2024-03-05',
        status: 'overdue',
        payments: [
          { id: 'p4', loanId: 'l4', amount: 1500, date: '2024-04-05', type: 'interest' },
        ],
      },
    ],
  },
];
